web:
  build: ./web
  command: python -u ./web/app.py
  ports:
    - "8008:8008"
  volumes:
    - .:/app
  links:
    - db
trawler:
  build: .
  command: python -u ./trawler.py --configuration ./config.conf
  volumes:
    - .:/app:Z
  links:
    - db
db:
  image: mongo:3.0.2
